USE [master]
GO

/****** Object:  Database [ConceptsRelationDB]    Script Date: 01/27/2019 18:16:01 ******/
CREATE DATABASE [ConceptsRelationDB] ON  PRIMARY 
( NAME = N'ConceptsRelationDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ConceptsRelationDB.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ConceptsRelationDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ConceptsRelationDB_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ConceptsRelationDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ConceptsRelationDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ConceptsRelationDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ConceptsRelationDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ConceptsRelationDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ConceptsRelationDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ConceptsRelationDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ConceptsRelationDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ConceptsRelationDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ConceptsRelationDB] SET  READ_WRITE 
GO

ALTER DATABASE [ConceptsRelationDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ConceptsRelationDB] SET  MULTI_USER 
GO

ALTER DATABASE [ConceptsRelationDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ConceptsRelationDB] SET DB_CHAINING OFF 
GO


