//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsRelation.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConceptsRelationDBEntities1 : DbContext
    {
        public ConceptsRelationDBEntities1()
            : base("name=ConceptsRelationDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConceptsRelation> ConceptsRelations { get; set; }
        public virtual DbSet<MasterFile> MasterFiles { get; set; }
        public virtual DbSet<RelationCategory> RelationCategories { get; set; }
    }
}
