//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsRelation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterFile
    {
        public int FileID { get; set; }
        public string Name { get; set; }
        public string FilePath { get; set; }
    }
}
